version: '3'

services:
  web:
    container_name: web
    build: .
    command:
     sh -c "python manage.py runserver 0.0.0.0:8000 &&
            python -m celery -A CardReader worker"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis 

  db:
    container_name: db
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - /nginx.conf
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  pgdbdata: