version: '3'

services:
  web:
    container_name: web
    build: .
    command:
     sh -c "python manage.py runserver 0.0.0.0:8000 &&
            python -m celery -A CardReader worker"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=cardreader
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kalabok76
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  redis:
    container_name: 'redis'
    image: redis:alpine
    expose:
      - 6379

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    ports:
#      - 80:80
#    volumes:
#      - /nginx.conf
#    depends_on:
#      - web

volumes:
  pgdbdata:
